apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - bg-configmap.yaml
  - helmchart.yaml


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: homepage-config
    files:
      - settings.yaml
      - widgets.yaml
      - kubernetes.yaml
    literals:
      - services.yaml=""
      - bookmarks.yaml=""
  # - name: homepage-bg
  #   files:
  #     - ./bg.jpg
  - name: homepage-custom-js
    files:
      - ./custom.js