background: 
  image: bg.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

headerStyle: underlined

layout:
  Homelab:
    style: row
    columns: 3
    useEqualHeights: true
  Media:
    style: row
    columns: 3
    useEqualHeights: true
  Widgets:
    style: row
    columns: 3
    useEqualHeights: true
  Monitoring:
    style: row
    columns: 3
    useEqualHeights: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

showStats: true