services:
  obsidian-livesync:
    image: couchdb:latest
    container_name: obsidian-livesync-couchdb
    restart: unless-stopped
    # ports:
      # - "5984:5984"
    environment:
      - COUCHDB_USER=${OBSIDIAN_COUCHDB_USER}
      - COUCHDB_PASSWORD=${OBSIDIAN_COUCHDB_PASSWORD}
    volumes:
      - /data/docker/volumes/obsidian-livesync-data:/opt/couchdb/data
      - /data/docker-volumes/obsidian-livesync-etc:/opt/couchdb/etc/local.d
